server <- function(input,output,session){
  output$chart_messages <- renderUI({
    mydata <- filterDropdowns(yaxistest,input$dateRange)
    selectInput('chart_messages','Messages',c('All Messages'='all_messages',unique(mydata$Message)))
  })
  output$summary_table <- DT::renderDataTable({makeSummaryTable(summary_table1,FALSE,c('Coalition','Channel'),c('Spend','Impressions','Engagements','True Engagements','Shares','Comments','Video Views','Video Completions','Website Clicks'),input$dateRange,input$channel,input$interest,input$theme,c(input$coalitionCheck),input$username,input$quadrant)})
  output$billing_table <- DT::renderDataTable({makeBillingTable(billing_lookup,invoices,input$dateRange)})
  output$invoices_table <- DT::renderDataTable({makeInvoicesTable(invoices,input$dateRange)})
  output$creative_table1 <- DT::renderDataTable({makeCreativeTableSmall(summary_table_cluster,FALSE,c('Channel','Coalition','Message'),c('Spend','Impressions','Engagements'),input$dateRange,input$channel,input$interest,input$quadrant,input$theme,input$message,c(input$percentCheckMsg,input$channelCheck,input$coalitionCheck),FALSE,input$username)})
  output$creative_table1a <- DT::renderDataTable({makeCreativeTableSmall(summary_table_cluster,FALSE,c('Channel','Coalition','Message'),c('Spend','Impressions','Engagements'),input$dateRange,input$channel,input$interest,input$quadrant,input$theme,input$message,c(input$percentCheckMsg,input$channelCheck,input$coalitionCheck),TRUE,input$username)})
  output$creative_table2 <- DT::renderDataTable({makeCreativeTableSmall(summary_table_cluster,FALSE,c('Channel','Coalition','Tone'),c('Spend','Impressions','Engagements'),input$dateRange,input$channel,input$interest,input$quadrant,input$theme,input$message,c(input$percentCheckTone,input$channelCheck,input$coalitionCheck),FALSE,input$username)})
  output$creative_table2a <- DT::renderDataTable({makeCreativeTableSmall(summary_table_cluster,FALSE,c('Channel','Coalition','Tone'),c('Spend','Impressions','Engagements'),input$dateRange,input$channel,input$interest,input$quadrant,input$theme,input$message,c(input$percentCheckTone,input$channelCheck,input$coalitionCheck),TRUE,input$username)})
  output$creative_table3 <- DT::renderDataTable({makeCreativeTableSmall(summary_table_cluster,FALSE,c('Channel','Coalition','Format'),c('Spend','Impressions','Engagements'),input$dateRange,input$channel,input$interest,input$quadrant,input$theme,input$message,c(input$percentCheckFormat,input$channelCheck,input$coalitionCheck),FALSE,input$username)})
  output$creative_table3a <- DT::renderDataTable({makeCreativeTableSmall(summary_table_cluster,FALSE,c('Channel','Coalition','Format'),c('Spend','Impressions','Engagements'),input$dateRange,input$channel,input$interest,input$quadrant,input$theme,input$message,c(input$percentCheckFormat,input$channelCheck,input$coalitionCheck),TRUE,input$username)})
  output$creative_image_table <- DT::renderDataTable({makeCreativeImageTable(summary_table_cluster,input$dateRange,input$interest,input$channel,input$username,input$theme,input$tone,input$quadrant,input$segment,input$creative_table_split,input$creative_table_metric)})
  output$creative_table4 <- DT::renderDataTable({makeCreativeTable(summary_table,FALSE,c('Date','Channel','Coalition','Campaign','Ad Group','Ad Name','Theme','Message','Tone','Format','Version','Political','Matrix Position'),c('Spend','Impressions','Engagements'),input$dateRange,input$channel,input$interest,input$theme,NULL)})
  output$reactions_table <- DT::renderDataTable({makeReactionTable(reactions_table1,FALSE,c('Channel','Coalition','Theme','Message','Tone'),c('Like','Love','Haha','Wow','Sad','Angry'),input$dateRange,input$channel,input$interest,input$theme,input$tone,input$message,c(input$percentCheck,input$coalitionCheck,input$themeCheck,input$toneCheck,input$messageCheck),FALSE,input$username)})
  output$reactions_tablea <- DT::renderDataTable({makeReactionTable(reactions_table1,FALSE,c('Channel','Coalition','Theme','Message','Tone'),c('Like','Love','Haha','Wow','Sad','Angry'),input$dateRange,input$channel,input$interest,input$theme,input$tone,input$message,c(input$percentCheck,input$coalitionCheck,input$themeCheck,input$toneCheck,input$messageCheck),TRUE,input$username)})
  output$spend_chart <- renderHighchart({summary_chart(c('Date','Channel','Matrix Position'),c('Spend','Reach','Impressions','Engagements','CumSpend','CumImpressions'),c(input$cumcheck),input$chartType,input$dateRange,input$interest,input$channel,input$chartsplit,input$username,input$quadrant,input$do,c('Spend','CumSpend'))})
  output$impression_chart <- renderHighchart({summary_chart(c('Date','Channel','Matrix Position'),c('Spend','Reach','Impressions','Engagements','CumSpend','CumImpressions'),c(input$cumcheck2),input$chartType2,input$dateRange,input$interest,input$channel,input$chartsplit2,input$username,input$quadrant,input$do,c('Impressions','CumImpressions'))})
  output$whitmer_sentiment <- renderText({getCoeffs(sentiment,'Gretchen Whitmer','sentiment',input$sentiment_range)})
  output$whitmer_change <- renderText({getCoeffs(sentiment,'Gretchen Whitmer','change',input$sentiment_range)})
  output$whitmer_mentions <- renderText({getCoeffs(sentiment,'Gretchen Whitmer','mentions',input$sentiment_range)})
  output$whitmer_positives <- renderText({getCoeffs(sentiment,'Gretchen Whitmer','pos_mentions',input$sentiment_range)})
  output$whitmer_negatives <- renderText({getCoeffs(sentiment,'Gretchen Whitmer','neg_mentions',input$sentiment_range)})
  output$schuette_sentiment <- renderText({getCoeffs(sentiment,'Bill Schuette','sentiment',input$sentiment_range)})
  output$schuette_change <- renderText({getCoeffs(sentiment,'Bill Schuette','change',input$sentiment_range)})
  output$schuette_mentions <- renderText({getCoeffs(sentiment,'Bill Schuette','mentions',input$sentiment_range)})
  output$schuette_positives <- renderText({getCoeffs(sentiment,'Bill Schuette','pos_mentions',input$sentiment_range)})
  output$schuette_negatives <- renderText({getCoeffs(sentiment,'Bill Schuette','neg_mentions',input$sentiment_range)})
  output$coefficient1 <- renderText({paste0('Sentiment (Linear Trend: ',plotSentiment(sentiment,c('Gretchen Whitmer',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'coeff',input$username,input$sentiment_range),')')})
  output$coefficient2 <- renderText({paste0('Sentiment (Linear Trend: ',plotSentiment(sentiment,c('Bill Schuette',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'coeff',input$username,input$sentiment_range),')')})
  output$coefficient3 <- renderText({paste0('Sentiment (Linear Trend: ',plotSentiment(sentiment,c(input$topic,input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'coeff',input$username,input$sentiment_range),')')})
  output$sentiment_chart1 <- renderHighchart(plotSentiment(sentiment,c('Gretchen Whitmer',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'trend',input$username,input$sentiment_range))
  output$sentiment_deltachart1 <- renderHighchart(plotSentiment(sentiment,c('Gretchen Whitmer',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'delta',input$username,input$sentiment_range))
  output$sentiment_stackedbar1 <- renderHighchart(plotSentiment(sentiment,c('Gretchen Whitmer',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'barchart',input$username,input$sentiment_range))
  output$mention_chart1 <- renderHighchart(mention_charts(mentions,c('Gretchen Whitmer',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,input$username,input$sentiment_range))
  output$sentiment_chart2 <- renderHighchart(plotSentiment(sentiment,c('Bill Schuette',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'trend',input$username,input$sentiment_range))
  output$sentiment_deltachart2 <- renderHighchart(plotSentiment(sentiment,c('Bill Schuette',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'delta',input$username,input$sentiment_range))
  output$sentiment_stackedbar2 <- renderHighchart(plotSentiment(sentiment,c('Bill Schuette',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'barchart',input$username,input$sentiment_range))
  output$mention_chart2 <- renderHighchart(mention_charts(mentions,c('Bill Schuette',input$topicLCV,input$topicPP,input$topicPM),input$dateRange,input$username,input$sentiment_range))
  output$sentiment_chart3 <- renderHighchart(plotSentiment(sentiment,c(input$topic,input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'trend',input$username,input$sentiment_range))
  output$sentiment_deltachart3 <- renderHighchart(plotSentiment(sentiment,c(input$topic,input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'delta',input$username,input$sentiment_range))
  output$sentiment_stackedbar3 <- renderHighchart(plotSentiment(sentiment,c(input$topic,input$topicLCV,input$topicPP,input$topicPM),input$dateRange,'barchart',input$username,input$sentiment_range))
  output$mention_chart3 <- renderHighchart(mention_charts(mentions,c(input$topic,input$topicLCV,input$topicPP,input$topicPM),input$dateRange,input$username,input$sentiment_range))
  output$newstable <- renderDT(makeNewsTable(news,c('Date','TextDate','Category','Summary','Link'),input$dateRangeNews,c(input$categoryNews,input$categoryNewsLCV,input$categoryNewsPP,input$categoryNewsPM),input$username),escape = FALSE)
  output$hashhigh <- renderHighchart(makeHighChartHashtags(hashtags, input$dateRange, input$categoryTwitter))
  output$display1 <- DT::renderDataTable({makeDisplay(dat1,input$username)})
  output$display2 <- DT::renderDataTable({makeDisplay(dat2,input$username)})
  output$display3 <- DT::renderDataTable({makeDisplay(dat3,input$username)})
  output$clusterGraph <- renderHighchart({plotQuadrant(yaxistest,input$dateRange,c('Spend','Impressions','Engagements'),c('Message','Gender','Ethnicity','Matrix Position','Psychographic Segment','Date'),input$xaxis,input$yaxis,input$quadrant,input$chart_messages)})
  output$survey_chart1 <- renderHighchart({plotSurvey(survey_new,'Matrix Position',FALSE)})
  output$survey_chart2 <- renderHighchart({plotSurvey(survey_new,'Matrix Position',FALSE,'delta1')})
  output$survey_table <- DT::renderDataTable({makeSurveyTable(survey_test)})
  output$scatter_plot <- renderHighchart({plotScatter(testplot2)})
  output$scatter_plot_survey <- renderHighchart({plotScatterSurvey(survey_new,input$surveyGroup)})
  observeEvent(input$do,{
    message <- 'OBSERVE ME'
    session$sendCustomMessage('handler1',message)
  })
}